
architecture: standalone

# Configuration for Postgres. Important: When you start database, these are going to be the default un,pw
# secretDotYaml file "postgress pw" MUST match values postgressYaml password. make not in readme file
auth:
  username: mysiteuser
  password: this-is-a-bad-password
  database: mysite
  postgresPassword: this-is-a-bad-password

# GKE Autopilot requires requests and limits.
primary:
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
      ephemeral-storage: "100Mi"
    limits:
      memory: "512Mi"
      cpu: "500m"
      ephemeral-storage: "100Mi"