
architecture: standalone

#Important: When initializing a database, this will be the default username and password. 
#Important: “POSTGRES_PASSWORD:'' in SECRET.YAML file MUST match values of “postgresPassword:”  in VALUES-POSTGRESS.YAML

auth:
  username: mysiteuser
  password: this-is-a-bad-password
  database: mysite
  postgresPassword: this-is-a-bad-password

# GKE Autopilot requires requests and limits.
primary:
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
      ephemeral-storage: "100Mi"
    limits:
      memory: "512Mi"
      cpu: "500m"
      ephemeral-storage: "100Mi"