apiVersion: v1
kind: Pod
metadata:
  name: django-pod
  labels:
    function: app
spec:
  containers:
  - name: django
    image: ghcr.io/oggsus/cis-92:milestone-6.3
    ports:
    - containerPort: 8000
    resources:
      requests:
        cpu: 250m 
        memory: 512Mi
        ephemeral-storage: 10Mi
      limits:
        cpu: 250m 
        memory: 512Mi
        ephemeral-storage: 10Mi
    env:
    - name: STUDENT_NAME
      value: "Jesus Gonzales"
    - name: SITE_NAME
      value: "*"